language: java

jdk:
   - oraclejdk8

script:
   - test $TRAVIS_BRANCH == "master" && gradle check
   
after_success:
   - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && gradle deploy
