language: java

jdk:
- oraclejdk8

after_success:
- gradle bintrayUpload

deploy:
  provider: s3
  access_key_id:
    secure: iyzl946oR899WwINQc3WYUlMcDwXiJXbfPIGTIlrp3GivHHwWH2HTL0wSo79THnrnxN8Pn+qioL0bAi3amgRn53/dgwmdv9kqrhz/lCgX6VwR6/F+kVTsLQhs85YzM5QcGmSkK6cdZfckfXh+iANzQzrJ4TONZiM+VZHlXsbAvfMVBq0FLzht7BP6YFaLQXd+ANYj0BvXK2y6C94wcSnI7ohOMkZnR1dtUvL46/psnm0zyAwLcbalz6JqJ4AS+yhabJzDXHWD9tOyahxPkC+AxOMvwQc9qLIRCBp6w8unpJ/pP3oDCXJZykJ5SQ5uPVqqJEv1WzDlmwYOzxkazMYFyuTB+DrnnRXSBCKFyipNPWIT0G12fRoRnhsU3e0UZdjsPELBoriHm0/Z5g7yJgGCTdqcGf6RlmEhkVcInPWFruqk7x1t7ofsq9f56MD78C1miHHHmFgiafEoK2ryYOohM+cIFpZtf8QekY2YYEzldP6pF/lEaqB/PbqTKw8BpXBRW6F0P0KZNW4TktSe13V1Ex/4EwAFKZbnjml51MVoL0srjXSuwxRWd1DmcYli35sK5qelk9CgpHxYKj7JuZs6cec7pZ55ND7+vSvMPAWAwNJo3HOoqno0E6WHMxb1qCf5k2Zv9AOmVQ3S4EXkX5tUpFwUZxBeb94n/OuJK9gfQg=
  secret_access_key:
    secure: mMx1/OM1CZ+y7QVlUcfqRsbYF6V3nGbeU4Nmfx2V1CnAeyfCcn8T09uexePRdb9w6v7+YHTF5IjGlyGmzLIxO2e8Za2knFPijkfl6MWKwCpJJstrdq1GZekTGlp27HYtI+fPE6g7RV5ktqv5NArb9h7Agf1J8PkZANtaJLmFvGTn/wIvK5bK9+MhglgmgD0AR1OPXs9mD/vf6DEK2kqrsgQ7N3cz76zCiS5Jzpd3o5DT6SkfTlKSztExTj1QZw7GZLyBtQGGnL7WW4fwjnIdG1x+psq4vL6bczE+9Yp7TX/Sx+TatVj9C7rD3xM0k/McJg4vSCXDRqdWFXGOl68+FrsTA1x9B8eJbkgKl9kEztd9G3y8JGgWE3ySNvwV6oaLlVHdWFHkO+3TGQG3otUK9pLxSrNMmKJkLJUsCpifG1PsiesGZYIXQ3/gFFAcxw55B0hLmf9GnZozVt4L0Ysywzki+a09NMiWO4tsliibUBfBWTt2egdd6l9ZEKA2CRbjm2zqYRpcK8+QXVw/MWVczLmBRbmtBNd+faYN7Lui48XqbygajuKjmnqnx1AffuIoGbTVdV0qHROPR17y1nYJn5X8zu9Yy9zv4/jvEQkBlQf9h6s3ZgL+BBdkwcZ/ROvjcOpIGkQj61f/1DsftJ2agCayEYtxuQZ+IAOAyngzzM4=
  bucket: marketstem
  skip_cleanup: true
  local_dir: build/libs
